"""add tournament_participant_members table for roster snapshots

Revision ID: baf2dc1bd3bd
Revises: eb030e9e4708
Create Date: 2026-09-16 13:16:42.477998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf2dc1bd3bd'
down_revision = 'eb030e9e4708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_participant_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_participant_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_participant_id'], ['tournament_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_participant_id', 'player_id', name='uq_tp_member')
    )
    with op.batch_alter_table('tournament_participant_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_participant_members_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_participant_members_tournament_participant_id'), ['tournament_participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_participant_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_participant_members_tournament_participant_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_participant_members_player_id'))

    op.drop_table('tournament_participant_members')
    # ### end Alembic commands ###
